name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - run: ./gradlew check

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: build/test-results/test/TEST-*.xml
          retention-days: 10
